### ISSUE TITLE
How to run these codes?

### ISSUE THREAD

**Issue by Yangshell** [wohlert/generative-query-network-pytorch#1]

**Comment by wohlert** [comment]
To train the model on Shepard Metzler 5 parts dataset:

1. Download the dataset from Google
2. Convert data to PyTorch format and put it in the same directory as the code
3. `python run-gqn.py --data_dir "shepard_metzler_5_parts/train"`

If you want to train it on a different dataset you must perform steps 1. and 2. Additionally, you should create a PyTorch dataset class for your new dataset.

I will put up a pretrained model later in the week.
