### ISSUE TITLE
GQN for 3d map reconstruction 

### ISSUE THREAD

**Issue by sharypovandrey** [wohlert/generative-query-network-pytorch#12]
Im working on building the robot for indoor use. 
Is it possible to use GQN to build a 3d map and localize the robot?
Thank you!

**Comment by wohlert** [comment]
Short answer: not with this code.

DeepMind did something similar with the GQN in this [paper](https://arxiv.org/abs/1807.03149) however, their results aren't very conclusive about whether it is possible learning an implicit map of the environment. Then you have the technical problem of actually making the GQN work.

**Comment by sharypovandrey** [comment]
Hello Jesper,
Thank you for your response. 
I’m looking to the side of CNN-SLAM
