### ISSUE TITLE
error in notebook

### ISSUE THREAD

**Issue by wasif26** [wohlert/generative-query-network-pytorch#15]
<ipython-input-28-6c9a644ebdbc> in <module>()
      1 f, axarr = plt.subplots(1, 15, figsize=(20, 7))
      2 for i, ax in enumerate(axarr.flat):
----> 3     ax.imshow(x[0][i].permute(1, 2, 0))

RuntimeError: number of dims don't match in permute

**Comment by wohlert** [comment]
Yes, the notebooks haven't been updated to reflect the new codebase.
