### ISSUE TITLE
Questions on data preparing

### ISSUE THREAD

**Issue by Kyridiculous2** [wohlert/generative-query-network-pytorch#16]
Hi, Wohlert:

After the data conversion with your scripts, I visualize some of the images in the *.pt 
found pictures like this
![Figure_1-1](https://user-images.githubusercontent.com/26832000/55151949-4ebf3000-518a-11e9-84a7-66fbca80bcab.png)
 
What's wrong with that 
Also I'm confused about your batch operation , say if you batch the sequences as you convert them, does it mean that you won't batch them again when use dataloader?

Thanks

**Comment by Kyridiculous2** [comment]
I do get a batch x 15 x 64 x64 x3 images, and I just imshow  each image after transpose to 64x64x3

**Comment by wohlert** [comment]
What you are seeing is the result of a wrong conversion of the tf-records, I had since changed this, but forget to commit these changes - they are added now. 

When we convert them we choose the batch size of the converted record, e.g. bs = 64. Then when we load them we choose an internal batch size of k*bs, usually k=1.

**Comment by Kyridiculous2** [comment]
Thanks for solving that, I've found it is because you extract imgs from tfrecord to 3x64x64 directly, it should be 64x64x3 and then converted.  
Still I visualize the images, found some imgs with multiple objects in it as it is mentioned in another issue, It seems that we can do nothing with that, are we? 
Last thing ,when you convert the tfrecord to batches, it seems there remains a batch less than 64 because the total num can't be divided by it, this will cause a problem when u use dataloader for batch the stored batches, I think i can fix this by add a collate function for the dataloader.

**Comment by wohlert** [comment]
yes, the problem is also referenced in issue [#11](https://github.com/wohlert/generative-query-network-pytorch/issues/11). For the batch problem you can probably fix it with a collate. Note that I am no longer working on this project, so I cannot provide in depth help.

**Comment by Kyridiculous2** [comment]
You've really done a great job, appreciate for that.
THANKS!
