### ISSUE TITLE
ConvLSTM did not concat hidden from last round

### ISSUE THREAD

**Issue by tomfox1900** [wohlert/generative-query-network-pytorch#17]
In the structure presented in the paper, the hidden from last round is concat with input and then proceed for other operation. But it seems your LSTM did not use the hidden information from previous round.

**Comment by wohlert** [comment]
Can you perhaps show me where you think this is the case?

The last hidden state of the generator LSTM is concatenated with the input and fed into the inference LSTM here:

https://github.com/wohlert/generative-query-network-pytorch/blob/master/gqn/generator.py#L146

**Comment by tomfox1900** [comment]
So the input fed into inference should be h_(i-1) + h_g + x + v + r, what I'm saying is it seems you missed the h_(i-1) part, which is the hidden state from last round of inference LSTM.

Similarly the generator LSTM.

**Comment by tomfox1900** [comment]
Another question I have is about the sigma scheme, I noticed you updated the shepardmetzler.py, and the range of data is from 0 to 1 now, but the sigma scheme is set to be 0.7 to 2, not sure if this will affect the log likelihood estimation.

**Comment by wohlert** [comment]
The h_(i-1) part is fed into the LSTM through the state variable, so the information is available to the network. You can see this at the end of the line that i linked.

The sigma scheme is the same as done in the paper. The authors never specify the data range, but it is customary to have it be floating points [0, 1].

**Comment by tomfox1900** [comment]
Check the following two lines:
https://github.com/wohlert/generative-query-network-pytorch/blob/master/gqn/generator.py#L53
https://github.com/wohlert/generative-query-network-pytorch/blob/master/gqn/generator.py#L62

The hidden state is fed in, but not used, and directly overwritten by the new hidden state.

**Comment by wohlert** [comment]
Yes, I see that is a mistake.

**Comment by wohlert** [comment]
It has been fixed in the recent commit. Thank you for posting this issue.
