### ISSUE TITLE
Convert tensorflow data to PyTorch format

### ISSUE THREAD

**Issue by mjchen611** [wohlert/generative-query-network-pytorch#2]
Hi,

How can I convert tensorflow data to PyTorch format?
Can you give me a source code or converted dataset?
Thank you,

Mingjia.

**Comment by wohlert** [comment]
I used this script [gqn_datasets_translator](https://github.com/l3robot/gqn_datasets_translator). However, it runs quite slow at the moment, so I have only been able to convert about 20% of the data.

**Comment by mjchen611** [comment]
Thank you for your kind assistance.

Mingjia
